//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIUCMachineAvailabilityService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class machinesEntities : DbContext
    {
        public machinesEntities()
            : base("name=machinesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Availability> Availabilities { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Lab> Labs { get; set; }
        public DbSet<Machine> Machines { get; set; }
    }
}
