//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIUCMachineAvailabilityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Availability
    {
        public int aid { get; set; }
        public System.DateTime adate { get; set; }
        public int fmid { get; set; }
        public bool mavailable { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
