//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIUCMachineAvailabilityService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Machine
    {
        public Machine()
        {
            this.Availabilities = new HashSet<Availability>();
            this.Events = new HashSet<Event>();
        }
    
        public int mid { get; set; }
        public int flid { get; set; }
        public string mname { get; set; }
        public string mmac { get; set; }
        public string mlkip { get; set; }
        public string mstat { get; set; }
        public string mlabel { get; set; }
        public string mtype { get; set; }
    
        public virtual ICollection<Availability> Availabilities { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual Lab Lab { get; set; }
    }
}
